[project]
name = 'Decentralized-Public-Library-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.book-registration]
path = 'contracts/book-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.borrowing]
path = 'contracts/borrowing.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-library-loan]
path = 'contracts/inter-library-loan.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-analytics]
path = 'contracts/usage-analytics.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
